
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImNyZWF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVwZGF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVzZXJpZCI6InlvbmcxMjM0IiwibmFtZSI6InlvbmciLCJwYXNzd29yZCI6IiQyYiQxMCRGVEpIalNOSC55Z2ljaVlZNDdZZTAueUFHMm9KVFpTMWptV0NacE0zc0FxNWFEUm1jQUZjVyIsInVzZXJuYW1lIjoieW9uZyIsImJpbyI6bnVsbCwiYXZhdGFyIjpudWxsLCJzdGF0dXMiOm51bGwsImlhdCI6MTY2MDExMjQ2NCwiZXhwIjoxNjYwMTEyNDc5fQ.BpDT2IrAd4t5_An9QI0Tf2XUTgsvAb-7DnW5xA_8gp8



###

POST http://localhost:8080/login
Content-Type: application/json

{
    "userid":"yong1234",
    "password":"12345678"
}


###

POST http://localhost:8080/token 
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImNyZWF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVwZGF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVzZXJpZCI6InlvbmcxMjM0IiwibmFtZSI6InlvbmciLCJwYXNzd29yZCI6IiQyYiQxMCRGVEpIalNOSC55Z2ljaVlZNDdZZTAueUFHMm9KVFpTMWptV0NacE0zc0FxNWFEUm1jQUZjVyIsInVzZXJuYW1lIjoieW9uZyIsImJpbyI6bnVsbCwiYXZhdGFyIjpudWxsLCJzdGF0dXMiOm51bGwsImlhdCI6MTY2MDExMzI1MX0.Y9tgfeq5PIXmT71MPhD8FxRPqtlXelZgknbritWHXfs"
}


###S
DELETE http://localhost:8080/logout
Content-Type: application/json
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImNyZWF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVwZGF0ZWRBdCI6IjIwMjItMDgtMTBUMDE6MzQ6NDAuMTc3WiIsInVzZXJpZCI6InlvbmcxMjM0IiwibmFtZSI6InlvbmciLCJwYXNzd29yZCI6IiQyYiQxMCRGVEpIalNOSC55Z2ljaVlZNDdZZTAueUFHMm9KVFpTMWptV0NacE0zc0FxNWFEUm1jQUZjVyIsInVzZXJuYW1lIjoieW9uZyIsImJpbyI6bnVsbCwiYXZhdGFyIjpudWxsLCJzdGF0dXMiOm51bGwsImlhdCI6MTY2MDEwODgzNn0.xxUtU6tUwYzoq3-ngTbv4ySxUr0OkWlYQ1D31UoCb6A"
}